# Generated by Django 4.1.3 on 2022-12-01 18:56

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_country_name_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=home.models.project_filename),
        ),
        migrations.AlterField(
            model_name='file',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to=home.models.preview_filename),
        ),
    ]
