# Generated by Django 4.1.3 on 2023-01-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_file_file_alter_file_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='product',
            new_name='crmProduct',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='productId',
            new_name='mysheetId',
        ),
    ]
